---
authors:
  - Ruchi Pakhle (Ruchip16)
  - Rohit Thakur (rohitthakur2590)
dependencies:
  "ansible.netcommon": ">=6.0.0"
  "ansible.utils": ">=3.0.0"
  "ansible.scm": ">=2.0.0"
license_file: LICENSE
name: healthchecks
description: Ansible Network Healthchecks collection enables users to perform various network health checks and monitoring tasks across different network platforms.
namespace: network
readme: README.md
repository: https://github.com/redhat-cop/network.healthchecks
issues: https://github.com/redhat-cop/network.healthchecks/issues
tags: [networking]
version: 1.0.0
