---
- name: Execute environment commands on Cisco NX-OS device
  when: ansible_network_os == "nxos"
  cisco.nxos.nxos_command:
    commands: "{{ environment_healthcheck_nxos_commands }}"
  register: env_output

- name: Execute environment commands on Arista EOS device
  when: ansible_network_os == "eos"
  arista.eos.eos_command:
    commands: "{{ environment_healthcheck_eos_commands }}"
  register: env_output

# - name: Skip environment check on Cisco IOS XR device
#   when: ansible_network_os == "iosxr"
#   ansible.builtin.debug:
#     msg: "Environment health check is not supported on Cisco IOS XR devices."

# - name: Display environment check output
#   when: env_output is defined
#   ansible.builtin.debug:
#     var: env_output.stdout_lines
