---
- name: Include validation tasks (ensure target platform is supported)
  ansible.builtin.include_tasks: validation.yml

- name: Include OS-specific Environment tasks {{ ansible_network_os.split('.')[2] }}
  ansible.builtin.include_tasks: "./{{ ansible_network_os.split('.')[2] }}.yml"
