---
- name: Include validation tasks (ensure platform is supported)
  ansible.builtin.include_tasks: validation.yml

- name: Include OS-specific Filesystem tasks {{ ansible_network_os.split('.')[2] }}
  ansible.builtin.include_tasks: "./{{ ansible_network_os.split('.')[2] }}.yml"

- name: Debug raw filesystem health data
  ansible.builtin.debug:
    var: fs_health

- name: Set health checks fact
  ansible.builtin.set_fact:
    health_checks: >-
      {{
        fs_health | network.healthchecks.filesystem_health_check_view(
          {
            'name': 'health_check',
            'vars': {
              'checks': [
                {
                  'name': 'filesystem_status_summary',
                  'filesystem_free_threshold': filesystem_free_threshold | default(10)
                }
              ],
              'details': details | default(false)
            }
          }
        )
      }}

- name: Filesystem health checks
  ansible.builtin.debug:
    var: health_checks
  failed_when: "'FAIL' == health_checks.result"
