---
galaxy_info:
  author: Ruchi Pakhle (@Ruchip16)
  description: >
    This role performs a file system health check on network devices.
    It lists file systems and their statuses by executing platform-specific commands:
      - Cisco IOS XR: "show filesystem"
      - Cisco IOS XE: "show file systems"
      - Cisco NX-OS: "dir bootflash:"
      - Arista EOS: "show file systems" and "dir flash:"
  license: Apache-2.0
  min_ansible_version: ">=2.15.0"
  platforms:
    - name: Cisco IOS XR
      versions:
        - ">= 6.0"
    - name: Cisco IOS XE
      versions:
        - ">= 3.0"
    - name: Cisco NX-OS
      versions:
        - ">= 9.0"
    - name: Arista EOS
      versions:
        - ">= 4.20"
dependencies: []
