---
- name: Include validation tasks (ensure target platform is supported)
  ansible.builtin.include_tasks: validation.yml

- name: Include OS-specific Uptime tasks {{ ansible_network_os.split('.')[2] }}
  ansible.builtin.include_tasks: "./{{ ansible_network_os.split('.')[2] }}.yml"

- name: Set health checks fact
  ansible.builtin.set_fact:
    health_checks: "{{ uptime_parsed | network.healthchecks.health_check_view(health_check) }}"
  vars:
    health_check:
      name: health_check
      vars:
        checks:
          - name: uptime
            min_uptime: "{{ lookup('vars', 'uptime_threshold_minutes') | default(1440) }}"
          - name: uptime_status_summary
