---
- name: Parse bgp summary
  ansible.utils.cli_parse:
    command: "show ip bgp summary"
    parser:
      name: ansible.netcommon.native
    set_fact: bgp_health

- name: Debug
  ansible.builtin.debug:
    var: bgp_health
