---
- name: Parse crash output for EOS
  ansible.utils.cli_parse:
    command: "show tech-support | include crash"
    parser:
      name: ansible.netcommon.native
    set_fact: crash_health

- name: Debug crash health
  ansible.builtin.debug:
    var: crash_health
