---
- name: Parse cores output for NX-OS
  ansible.utils.cli_parse:
    command: "show cores"
    parser:
      name: ansible.netcommon.native
    set_fact: crash_health

- name: Debug crash health
  ansible.builtin.debug:
    var: crash_health
