---
- name: Include validation tasks (ensure platform is supported)
  ansible.builtin.include_tasks: validation.yml

- name: Include OS-specific CPU tasks {{ ansible_network_os.split('.')[2] }}
  ansible.builtin.include_tasks: ./{{ ansible_network_os.split('.')[2] }}.yml

- name: Set health checks fact
  ansible.builtin.set_fact:
    health_checks: "{{ cpu_health | network.healthchecks.health_check_view(health_check) }}"
  vars:
    health_check:
      name: health_check
      vars:
        checks:
          - name: cpu_utilization
            threshold: "{{ lookup('vars', 'cpu_threshold') | default(80) }}"
          - name: cpu_status_summary
