---
- name: Include validation tasks (ensure platform is supported)
  ansible.builtin.include_tasks: validation.yml

- name: Include OS-specific CPU tasks {{ ansible_network_os.split('.')[2] }}
  ansible.builtin.include_tasks: ./{{ ansible_network_os.split('.')[2] }}.yml

- name: Debug raw CPU health data
  ansible.builtin.debug:
    var: cpu_health

- name: Set CPU thresholds and details
  ansible.builtin.set_fact:
    details: "{{ cpu_utilization.details | default(false) }}"
    warning_threshold: "{{ cpu_utilization.warning_threshold | default(cpu_warning_threshold) }}"
    critical_threshold: "{{ cpu_utilization.critical_threshold | default(cpu_critical_threshold) }}"

- name: Set health checks fact
  ansible.builtin.set_fact:
    health_checks: >-
      {{
        cpu_health | network.healthchecks.health_check_view(
          checks,
          details=details,
          warning_threshold=warning_threshold,
          critical_threshold=critical_threshold
        )
      }}
  vars:
    checks:
      - name: cpu_utilization

- name: CPU health checks
  ansible.builtin.debug:
    var: health_checks
  failed_when: "'FAIL' == health_checks.result"
